services:
  postgres:
    image: postgres:15
    container_name: biblioteca-postgres
    restart: always
    environment:
      POSTGRES_DB: biblioteca_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - biblioteca-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

backend:
  image: anghelomp/biblioteca-virtual-backend:latest
  container_name: biblioteca-backend

  restart: always

  depends_on:
    postgres:
      condition: service_healthy

  ports:
    - "8080:8080"

  environment:
    SPRING_PROFILES_ACTIVE: docker

    DB_URL: jdbc:postgresql://postgres:5432/biblioteca_db
    DB_USERNAME: postgres
    DB_PASSWORD: postgres

    JWT_SECRET: miClaveSecretaMuySeguraParaJWT2025BibliotecaVirtual

    CLOUDINARY_CLOUD_NAME: tu_cloud_name
    CLOUDINARY_API_KEY: tu_api_key
    CLOUDINARY_API_SECRET: tu_api_secret

  networks:
    - biblioteca-net

  frontend:
    image: anghelomp/biblioteca-virtual-frontend:latest
    container_name: biblioteca-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - biblioteca-net

volumes:
  postgres_data:

networks:
  biblioteca-net:
    driver: bridge
