spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca_db
spring.datasource.username=postgres
spring.datasource.password=AngheloMPSQL10!
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=miClaveSecretaMuySeguraParaJWT2025BibliotecaVirtual
jwt.expiration=8640000

cloudinary.cloud_name=dlkijz9zn
cloudinary.api_key=532325122754565
cloudinary.api_secret=29Jt__lU9uxyPGZz7gPBW-2V55w